### ISSUE TITLE
Could it be possible to make iptstate compatible with nftables?

### ISSUE THREAD

**Issue by q2dg** [jaymzh/iptstate#16]
Thanks!

**Comment by jaymzh** [comment]
I'm surprised `libnetfilter_conntrack` (what we use) doesn't already support nftables...

**Comment by q2dg** [comment]
Well, it seems it's some kind of low-level problem with my system because _conntrack -L_ doesn't show anything neither. In fact, I've filled an "issue" here (https://ask.fedoraproject.org/t/conntrack-l-doesnt-show-anything/5894)...I don't know if I'll get any answer. 

Anyway, I'll close this issue because it seems it's not iptstate's fault.

Thanks a lot for your patiente
